---
- name:
  hosts: all
  becoe: true
  vars:
    git_repository: "https://github.com/gusiak97/Ansible_roles.git"
    git_branch: "main"
  tasks:
    - name: Create dir
      file:
        path: /etc/ansible/roles
        state: directory
        mode: '0755'
    - name: Git checkout
      git:
        repo: "{{ git_repository }}"
        dest: "/etc/ansible/roles"
        version: "{{ git_branch }}"